# Generated by Django 5.2.5 on 2025-09-01 03:46

import ckeditor.fields
import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_notalibre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nota',
            name='descripcion',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notalibre',
            name='contenido',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
